version: '3'
services:
  testApi:
    build:
      context: .
      dockerfile: DockerfileFunction
    image: gcp-test-api:latest
    container_name: testApi
    environment:
      ENV: local
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/test-account.json
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 9991:8080
    networks:
      - default
    command: sh -c "yarn install && yarn dev:compile && yarn dev:api-start"

networks:
  default:
    driver: bridge
